### ISSUE TITLE
Safari/Firefox mit hoher CPU Last

### ISSUE THREAD

**Issue by bseber** [urlaubsverwaltung/zeiterfassung#118]
Hat die Startseite mehrere Einträge, dann ist die CPU Last im Safari anscheinend recht hoch.

**Comment by honnel** [comment]
Die CPU Auslastung geht mit Firefox während laufender Zeiterfassung sehr hoch im Vergleich zum Chrome
https://user-images.githubusercontent.com/142107/221204476-85dd59ca-b213-43fc-bf09-c73036674ec0.mov
