### ISSUE TITLE
Sortierung innerhalb einer Woche nach Tag und nicht nach Datum

### ISSUE THREAD

**Issue by honnel** [urlaubsverwaltung/zeiterfassung#128]
Die Tagesblöcke innerhalb einer Woche werden aktuell nach "Tag" geordnet, nicht nach Datum. 

Z.B. die KW 5 2023 sieht das wie folgt aus:
**31.01**, **30.01**, 05.02, 04.02, 03.02, 02.02, 01.02

Erwarten würde man diese Reihenfolge:
05.02, 04.02, 03.02, 02.02, 01.02, **31.01**, **30.01**

![image](https://user-images.githubusercontent.com/142107/217454089-e2e5c8c6-59c1-4987-9bae-c7957d52f4da.png)

**Comment by derTobsch** [comment]
done in #129
