### ISSUE TITLE
Pause an der Stoppuhr nicht auswählbar

### ISSUE THREAD

**Issue by honnel** [urlaubsverwaltung/zeiterfassung#131]
![grafik](https://user-images.githubusercontent.com/142107/217794675-b46ff6cf-dd3c-46c5-a2d3-74c3768955e6.png)

Wenn ich versuche eine Stoppuhr als Pause zu setzen kommt beim Klick auf "Aktualisieren" der Fehler "Startzeit muss in der Vergangenheit liegen."

**Comment by derTobsch** [comment]
@honnel kann ich nicht nachstellen. Lass nachher mal zusammen schauen

**Comment by honnel** [comment]
![pause-timer](https://user-images.githubusercontent.com/142107/218093317-48430415-8b49-4633-8dd3-2826446d4bbf.gif)

**Comment by derTobsch** [comment]
Ist auf dem aktuellen "main" branch gefixt. Falls es nochmal auftritt machen wir dieses Ticket nochmal auf.
