### ISSUE TITLE
Länge einer Pause anzeigen

### ISSUE THREAD

**Issue by honnel** [urlaubsverwaltung/zeiterfassung#158]
Als Benutzende möchte ich die Länge meiner Pause sehen können, um zu wissen, ob ich heute schon genug Pause gemacht habe.
Aktuell wird bei allen Pausen immer 00:00 angezeigt, egal wie lange sie war.

![grafik](https://user-images.githubusercontent.com/142107/218557168-1bc2f02f-da0d-44da-a8f1-40a740ba876c.png)

**Comment by bseber** [comment]
fixed mit #153 ([commit a5faf323](https://github.com/urlaubsverwaltung/zeiterfassung/commit/a5faf32353f149d55ba037a8d9e349b27b8730a1))
