### ISSUE TITLE
Authenfizierung mit LDAP?

### ISSUE THREAD

**Issue by vreinen** [urlaubsverwaltung/zeiterfassung#239]
Moin zusammen,

ein paar Probleme mit der zeiterfassung.
wie kann die Zeiterfassung auf LDAP umgestellt werden?
Wie kann ich mich initial bei der Zeiterfassung bzw. keycloak anmelden? 
Nach dem Aufruf von http://myserver:8080/ bekomme ich die Meldung "Ungültiger Parameter: redirect_uri".

Vielen Dank im voraus und viele Grüße
Volker

**Comment by grafjo** [comment]
Hi @vreinen 
ldap ist nicht vorgesehen, für Keycloak könntest du dir die Konfigurationsoptionen der Zeiterfassung unter https://github.com/urlaubsverwaltung/zeiterfassung/blob/main/.examples/docker-compose/docker-compose.yml anschauen

**Comment by vreinen** [comment]
Moin grajo,
Mit diesem Beispiel habe ich die Container zu laufen bekommen (mit einer Änderung im keycloak build: ../../docker/keycloak auf build: docker/keycloak). Aber ich bekomme bei dem Aufruf die obengenannte  Fehlermeldung. Es scheint hier das Zusammenspiel zwischen zeiterfassung und keycloak zu haken.
Wer ist der initiale Nutzer? Oder wo trag ich ihn ein? SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-ID oder SPRING_DATASOURCE_USERNAME oder ...

Viele Grüße
Volker
