### ISSUE TITLE
Readonly Rolle

### ISSUE THREAD

**Issue by ghost** [urlaubsverwaltung/zeiterfassung#325]
Eine Readonly Rolle soll nutzern gegeben werden können, sodass diese ausschließlich ihre Zeiten lesen aber nicht eintragen können. Im Einklang mit NFC/RFID Tags könnte somit eine Umgebung geschafft werden, in welchem Nutzer nur mit diesen ihre Zeiten buchen können (siehe https://github.com/urlaubsverwaltung/zeiterfassung/issues/98).

**Comment by gillesromer** [comment]
Eine Alternative zu den Tags wäre https://github.com/urlaubsverwaltung/zeiterfassung/issues/325.

Im Allgemeinen geht es darum, dass dem/der Arbeitnehmer*in nicht zu 100% bei der Eintragung der Arbeitszeiten zu Vertrauen ist. Beispielsweise könnte diese*r sich um 8:00 Uhr eintragen und dabei erst 10 min später zur Arbeit gekommen sein. Eine Eintragung durch einen Supervisor oder durch Scannen einer Karte würde dieses Problem beheben.
