### ISSUE TITLE
Die App installierbar machen

### ISSUE THREAD

**Issue by hackschnitzel09** [urlaubsverwaltung/zeiterfassung#387]
Hi, 
es wäre mega cool wenn die Webapp installierbar wäre. In HTML: `<meta name="mobile-web-app-capable" content="yes">`
Viele Grüße

**Comment by stevleibelt** [comment]
@hackschnitzel09 

Ich habe mich über das HTML-Tag informiert.
Es ist weit mehr als nur das Tag einzupflegen. Man muss sich um die Navigation kümmern (die Browser-UI mit Zurück-Knopf fehlt zum Beispiel).
Darüber hinaus klappt das nur, wenn die Anwendung auch offlinefähig ist (lokaler Speicher, Mechanik zum Abgleich des lokalem Speichers mit der Datenbank wenn die Anwendung mal wieder "online" ist).

Die Idee ist natürlich super, der Arbeitsumfang ist etwas mehr :-).
