### ISSUE TITLE
Owntracks impelmentation

### ISSUE THREAD

**Issue by hackschnitzel09** [urlaubsverwaltung/zeiterfassung#388]
Hi,
ich hab gelesen die UV integration soll per rabbitmq funktionieren da kam die Idee auf Owntracks anzubinden. Owntracks sendet Geo Daten über MQTT und man kann Events erstellen wenn man eon Gebiet betritt bzw. Verlässt damit könnte man automatisch ein und ausstempeln lassen

**Comment by grafjo** [comment]
Hi @hackschnitzel09 an sich könnte man einen Event-Listener für Owntracks implementieren.
Wenn du ein solches Tracking implementierst beachte jedoch, dass es dabei zu rechtlichen Fragestellungen kommen kann, ob eine Arbeitgeberin Mitarbeitende in diesem Umfang tracken darf.

**Comment by hackschnitzel09** [comment]
Ja stimmt ich nutze es nur privat für mich. IM Geschäftsumfeld wäre das sicherlich nicht rechtens
