### ISSUE TITLE
Stundenüberblick in den Berichten

### ISSUE THREAD

**Issue by hackschnitzel09** [urlaubsverwaltung/zeiterfassung#389]
Hi, 
was mir fehlt ist eine Zahl im Berichts Tab. Beispielsweise wenn ich in der Wochen Ansicht bin wie rechts daneben wie viele Stunden ich im Plus oder Minus bin genauso im Monats Tab. Bisher muss ich immer den Bericht ziehen und dann dort rumrechnen.
Grüße

---

Folgende Werte sollten wir in den Berichten ergänzen:
- Soll-Tageszeit
- Ist-Tageszeit
- Tages-Über-/Unterstunden
- Summen dieser Werte pro Woche / Monat

**Comment by stevleibelt** [comment]
Hallo @hackschnitzel09,

ist es Ihnen möglich, mit Hilfe eines Bildschirmfotos und einfacher Bearbeitungsmagie, eine Art "Feature-Beispiel" zu erzeugen und anzuhängen?

Ich glaube, dass die gewünsche Funktionalität praktisch ist :-).

**Comment by hackschnitzel09** [comment]
![IMG_20231213_094809.jpg](https://github.com/urlaubsverwaltung/zeiterfassung/assets/51826763/fc53e891-116f-4d6e-a736-b79df030ae30)

Hi, in der mobilen Ansicht z.b. wo das X ist "Diese Woche +X Stunden" und wenn man auf den Monat wechselt "Diesen Monat +X Stunden".

Die Idee dahinter ist, dass ich wochentlich oder monatlich die Überstunden in die Urlaubsverwaltung übertragen kann ohne einen Report zu erzeugen zu müssen oder selbst zu rechen :)

**Comment by stevleibelt** [comment]
Danke @hackschnitzel09 

Ich hoffe, dass die Entwickler so einen bessern Einblick über den Funktionswunsch haben.
Ich mag ihn sehr :-).

**Comment by honnel** [comment]
Folgende Werte sollten wir in den Berichten ergänzen:
- Soll-Tageszeit
- Ist-Tageszeit
- Tages-Über-/Unterstunden
- Summen dieser Werte pro Woche / Monat

**Comment by scoopex** [comment]
Vielleicht könnt ihr bei der Gelegenheit gleich auch an direkt in den Anwendung (z.B. in der Buchungsansicht) und im Berichtsmenü direkt anzeigen?
(so das man sich das nicht erst downloaden muss)

**Comment by honnel** [comment]
wurde angefragt

**Comment by honnel** [comment]
wurde nochmal angefragt
