### ISSUE TITLE
Individuelle Abwesenheitsarten der Urlaubsverwaltung integrieren

### ISSUE THREAD

**Issue by bseber** [urlaubsverwaltung/zeiterfassung#425]
Die Urlaubsverwaltung unterstützt ab demnächst [individuellen Abwesenheitsarten](https://github.com/urlaubsverwaltung/urlaubsverwaltung/pull/4200).
Diese müssen wir in die Zeiterfassung integrieren.

TODOs:
* Vorarbeit: https://github.com/urlaubsverwaltung/zeiterfassung/issues/426
  * in einem späteren Schritt kann das DB Schema der `Absence` migriert werden
* https://github.com/focus-shift/urlaubsverwaltung-extension-api/issues/25

**Comment by honnel** [comment]
Wir sollten ebenfalls die Local bzw den Fallback analog zu https://github.com/urlaubsverwaltung/urlaubsverwaltung/issues/4660 bauen
