### ISSUE TITLE
Grafik im Monatsbericht zeigt falsche Menge an

### ISSUE THREAD

**Issue by aendi** [urlaubsverwaltung/zeiterfassung#467]
In der Wochenansicht sieht man die korrekte Darstellung. Im Monatsbericht sind die Balken zu hoch. 

<img width="1095" alt="Screenshot 2023-11-22 at 21 40 51" src="https://github.com/urlaubsverwaltung/zeiterfassung/assets/2080241/e0a2ff31-a624-460b-99cd-989d9441149a">

<img width="704" alt="Screenshot 2023-11-22 at 21 42 37" src="https://github.com/urlaubsverwaltung/zeiterfassung/assets/2080241/d61f6e19-2ea3-448e-bae6-a8d97a46f4f1">

**Comment by honnel** [comment]
Sieht so aus, wie als wäre das bereits gelöst
