### ISSUE TITLE
Public Holidays

### ISSUE THREAD

**Issue by hackschnitzel09** [urlaubsverwaltung/zeiterfassung#514]
Hi, 
I hope this idea was not already metioned.
Id love to be able to import public holidays because at the moment everything handles that day as not worked which reults in lack of working hours.

Kind regards

**Comment by bseber** [comment]
hey @hackschnitzel09. public holidays are handled in https://github.com/urlaubsverwaltung/zeiterfassung/issues/259 which may be published with the next release, or the following 🙃
