### ISSUE TITLE
Zeiterfassung mit Authentik

### ISSUE THREAD

**Issue by Xank-Devel** [urlaubsverwaltung/zeiterfassung#615]
Hallo,

ich habe mich, mit der Zeiterfassung beschäftigt und habe einige Probleme schon lösen können.
Ich verwende kein Keycloak, sondern Authentik (da wir das schon anderweitig verwenden) um Benutzer unserer Domäne mit anderen Softwarelösung zu verbinden. Aktueller Stand ist so, dass das Login super Funktioniert. Aber ich kriege nicht die Berechtigungen um z.B. die Benutzer Verwalten zu können. In OpenID sind diese (eure) Berechtigungen alle in "groups" und "roles" enthalten. Werden aber anscheinend nicht ausgewertet. Fehlt mir da noch eine Bestimmte Berechtigung? Habe heute auch noch mal eine neue VM gebaut mit PostgreSQL 16.0.2, Keycloak 24.0.1 und Zeiterfassung 2.1.2. Und habe da das selbe Problem.

Mit Keycloak --> Granted Authorities=[OIDC_USER, SCOPE_email, SCOPE_openid, SCOPE_profile, ZEITERFASSUNG_USER]
Mit Authentik --> Granted Authorities=[OIDC_USER, ZEITERFASSUNG_USER]

**Comment by mrbreil** [comment]
Ich habe das gleiche Problem, hast du eine Lösung gefunden.
