### ISSUE TITLE
Uhrzeiten sind im CSV Export nicht enthalten

### ISSUE THREAD

**Issue by tabacha** [urlaubsverwaltung/zeiterfassung#639]
**Is your feature request related to a problem? Please describe.**

Ich würde mit dem CSV Export auch gerne auswerten wie lange ich nicht gearbeitet habe etc. dafür brauche ich auch die Uhrzeiten. Die sind aber nicht enthalten.

Auch die DSGVO schreibt vor, dass jeder auf Anfrage alle seine Daten bekommen soll.
Um den Aufwand klein zu halten, sollten Tools deshalb auch alle Daten zu einer Person exportieren.

**Describe the solution you'd like**

Ich fände es gut die Uhrzeiten mit im CSV zu speichern.

**Optionally describe alternatives you've considered**

Ich sehe keine alternativen.

**Optionally additional context**

**Comment by honnel** [comment]
@tabacha Darf ich fragen, warum möchtest du wissen wie lange zu nicht gearbeitet hast? Welche Motivation steckt dahinter?
Eventuell ist der CSV Export und dessen Ausrichtung an der Stelle nicht das richtige, um einer DSGVO Anfrage gerecht zu werden.

**Comment by tabacha** [comment]
Also ich will mir z.B. ein Skript schreiben was prüft ob ich die Pausenzeiten und Ruhezeiten einhalte. Auch würde ich mit dem Skript bestimmte Postionen die ich in der Rufbereitschaft mache abrechnen, und meine Firma braucht dazu auch die Uhrzeiten, weil z.B. Nachtarbeit vom Kunden anders bezahlt werden muss.

Gibt es denn irgend einen Grund die Uhrzeiten nicht mit anzugeben? Wer sie nicht braucht, kann sie ja ignorieren oder mit Excel und co einfach entfernen.

Ob das mit der DSGVO Anfrage die richtige Ausrichtung ist, ist mir egal. Ist halt ein Mittel um Anbieter von Software zu zwingen keine Datensilos zu machen aus den man bestimmte Daten nicht mehr rausbekommt, und das scheint mir hier (ob wissentlich oder unwissentlich ist mir egal) der Fall zu sein. Ich finde es müßig darüber zu diskutieren ob meine Anforderung nun nach DSGVO erfüllt werden müsste oder nicht.

**Comment by honnel** [comment]
@tabacha Danke für dein Feedback! 
Nehmen wir gerne mit auf. Ich hatte einfach nur aus Interesse gefragt, um besser verstehen zu können.

Bezüglich der DSGVO Thematik: Ich denke nicht, dass der CSV-Export der Zeiteinträge (mit oder ohne Uhrzeiten) ausreichend ist, um Anfragen auf Auskunft nach Art. 15 Abs. 3 DSGVO gerecht zu werden. Dass es dabei um ein wichtiges Thema handelt, steht außer Frage.

> Ist halt ein Mittel um Anbieter von Software zu zwingen keine Datensilos zu machen aus den man bestimmte Daten nicht mehr rausbekommt, und das scheint mir hier (ob wissentlich oder unwissentlich ist mir egal) der Fall zu sein.

Dem "Datensilo" möchte ich widersprechen, da du die Software ja selbst betreiben kannst und somit mit einem Datenbank-Dump jederzeit machen kannst, was du möchtest.

**Comment by honnel** [comment]
Wurde angefragt

**Comment by aendi** [comment]
wurde angefragt
