### ISSUE TITLE
Prüfung gemäß deutschen Arbeitszeitgesetz

### ISSUE THREAD

**Issue by tabacha** [urlaubsverwaltung/zeiterfassung#640]
**Is your feature request related to a problem? Please describe.**

Wenn man sich nicht ans deusche Arbeitszeitgesetz hält, ist das eine Ordnungwidrigkeit für die sowohl der Arbeigeber, als auch der Arbeitnehmer bestraft werden kann.

**Describe the solution you'd like**

Es wäre gut, wenn das Tool zumindest warnt, wenn man z.B. wegen 
* zu wenig  Pausen oder 
* Ruhezeiten oder  (30 Minuten wenn man >6h Arbeitet, 45 min > 9h)
* Maximalzeiten (mehr als 10h Arbeiten innerhalb von 24h)

eine Ordnungswidrigkeit begeht, damit man das nach Möglichkeit eben nicht macht.

Dazu eine Einstelung auf Systemebene (für die Firma) ob man diese Warnungen wünscht oder nicht (weil z.B. die Firma gar nicht in Deutschland ist)

**Optionally describe alternatives you've considered**

keine Idee

**Optionally additional context**

* https://www.gesetze-im-internet.de/arbzg/BJNR117100994.html
* https://www.verdi.de/themen/arbeit/++co++3a8fac4e-0069-11ee-8da9-001a4a160129

**Comment by honnel** [comment]
@tabacha danke für das Issue! Wir haben das Thema bereits auf unserer Roadmap mit https://github.com/urlaubsverwaltung/zeiterfassung/issues/94. Deine Beschreibung macht die Relevanz nochmal deutlich.

**Comment by tabacha** [comment]
Moin,

Ticket #94 ist aber nur ein Teilaspekt. 

Es geht ja auch darum dass ich innerhalb von 24h nur 10h Arbeiten darf.

Also ich darf z.B. nicht gestern von 9 Uhr bis 18 Uhr mit 1h Pause (8h) und dann in der Rufbereitschaft noch mal von 21 Uhr bis 23 Uhr und dann heute um 8 Uhr anfangen weil dann ja mehr als 10h.

Und durch die  Ruhezeiten von 11h ab 22 Uhr würde dann bedeuten dass man erst um 10 Uhr anfangen darf.
