### ISSUE TITLE
Einrichtung und Anmeldung

### ISSUE THREAD

**Issue by sebierd** [urlaubsverwaltung/zeiterfassung#93]
Hallo zusammen, 

wir nutzen schon eure Urlaubsverwaltung erfolgreich und haben nun auch das Problem,d as wir die Arbeitszeiten erfassen müssen. 

Ist es auch möglich sich ohne OIDC anzumelden? Wir haben leider nicht die Möglichkeit einen entsprechenden Dienst zu etablieren und können nur auf ein Windows AD zurückgreifen. Mit der UV funktioniert das super. 

Wie kann ich die Properties anpassen, bevor ich den Container starte? Logischerweise bekomme ich Fehlermeldung, weil ich keine Datenbank angegeben habe. 

Zum Thema Datenbank: Plant ihr die Anbindung an die Urlaubsverwaltung? Also das man eine Datenbank verwenden kann, oder müssen die getrennt bleiben? 

Liebe Grüße
Sebie

**Comment by grafjo** [comment]
Hallo @sebierd

es gibt keine Möglichkeit sich ohne OIDC anzumelden. Wie @TORAMBO schon geschrieben hat, könnte für dich ein Weg sein über Keycloak ein Windows AD zu integrieren. Details dazu findest du im Keycloak Server Administration Guide unter [Using external storage](https://www.keycloak.org/docs/latest/server_admin/#_user-storage-federation) [](https://www.keycloak.org/docs/latest/server_admin/#_ldap)

Zum Thema Datenbank:
Stand jetzt (Januar 2023) wird hierfür eine eigene Datenbank benötigt, da die Zeiterfassung eine Postgresql benötigt und die Urlaubsverwaltung noch mit Mariadb / Mysql unterwegs ist. Dies könnte sich in Zukunft ändern, wenn von der Urlaubsverwaltung die Version 5 released wurde. Details siehe https://github.com/urlaubsverwaltung/urlaubsverwaltung/pull/3554
Es sei angemerkt, dass man später eventuell die selbe Datenbankinstanz verwenden kann, jedoch werden beide Anwendungen dedizierte Schemata innerhalb der Datenbankinstanz verwenden.

Zusätzlich möchte ich dich bitten für Fragen und Anregungen Rund um die Zeiterfassung Github [discussions](https://github.com/urlaubsverwaltung/zeiterfassung/discussions) zu verwenden, anstatt Issues - thx.
