### ISSUE TITLE
Dokumentation benötigt: Konfiguration der Abwesenheits-Synchronisation mit der Urlaubsverwaltung

### ISSUE THREAD

**Issue by implogy** [urlaubsverwaltung/zeiterfassung#966]
Ich versuche die Abwesenheits-Synchronisation zwischen Zeiterfassung und Urlaubsverwaltung einzurichten. Beide Anwendungen laufen in Docker-Containern und ich habe folgendes konfiguriert:

1. Einen gemeinsamen Keycloak-Realm für beide Anwendungen
2. Service-Account für die Zeiterfassung in Keycloak mit entsprechenden Rollen
3. Basis OAuth2/OIDC Konfiguration in der docker-compose.yml

Allerdings finde ich keine Dokumentation zu:
1. Welche Umgebungsvariablen für die Synchronisation benötigt werden
2. Wie die Verbindung zwischen Zeiterfassung und Urlaubsverwaltung konfiguriert wird
3. Ob es weitere notwendige Konfigurationsschritte gibt

Fragen:
1. Welche Konfiguration wird benötigt, um die Abwesenheits-Synchronisation zu aktivieren?
2. Wie kann man überprüfen, ob die Synchronisation funktioniert?
3. Gibt es Dokumentation zu diesem Feature?

Über Hilfe oder Dokumentation würde ich mich sehr freuen!

**Comment by grafjo** [comment]
Hi @implogy,
die Abwesenheits-Synchronisation gibt es ausschließlich in unserem Saas-Angebot der Urlaubsverwaltung / Zeiterfassung unter https://urlaubsverwaltung.cloud/ - deswegen findest du hierfür auch keine Dokumentation.
